name: "PR Bundle Analyzer"
description: "Github action to analyse your build bundle and show stats difference with the Base branch."
author: "BharatPe"
inputs:
  install_command:
    description: "cli command for installing dependencies ex npm install"
    required: true
    default: "npm install"
  build_command:
    description: "cli command for building repository ex npm run build"
    required: true
    default: "npm run build"
  build_path:
    description: "output path for the build package"
    required: true
    default: "build/static"
  base_branch:
    description: "Branch on which your feature branch will get merge ex. main"
    required: true
    default: "main"
  head_branch:
    description: "Branch in which your new changes exists ex. dev"
    required: true
    default: "main"
  token:
    description: "The token to use to access the GitHub API"
    required: true
  file:
    required: true
    description: "file name/path to edit. e.g 'package.json'"
  field:
    required: true
    description: "field to edit. can be nested fields. e.g 'version' or 'metadata.scripts.build'"
  value:
    required: true
    description: "value to set. string. e.g. 'v1.2.3'"
  parse_json:
    required: false
    default: ""
    description: "optional. if set to any non-empty value will parse the data in 'value' field to JSON"

runs:
  using: "node16"
  main: "dist/index.js"
outputs:
  size:
    description: "Build Size Difference"
branding:
  icon: "hard-drive"
  color: "blue"
