name: 'PR Bundle Analyzer'

on: [pull_request]

jobs:
  Calculate-Bundle-Difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
      - uses: bharatpe/pr-bundle-analyzer@main
        with:
          install_command: 'yarn install'
          build_command: 'yarn run build'
          build_path: 'build/static'
          base_branch: ${{ github.base_ref }}
          head_branch: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
